"""
AdviceIT by Radit, ml/fetch_ils_bench.py
---------------------------------------------------------------
Downloads the ILS-Bench dataset from Mendeley Data and extracts the
case-level table used to train the neural-network advisor.

    pip install openpyxl
    python3 fetch_ils_bench.py

Writes
    data/ILS_Bench_Repository.xlsx      the original file, as downloaded
    data/ils_bench_cases.csv            Cases_Consensus sheet, selected columns
    ../ils_bench_cases.js               same rows as a JS bundle for the app

Dataset
    Bonelli, M. (2026). ILS-Bench: Investor Language-to-Suitability
    Benchmark. Mendeley Data, V1. doi:10.17632/w48mh2dtg5.1
    Licence CC BY 4.0. 400 AI-assisted synthetic investor narratives,
    each validated by four independent financial-domain experts, with
    consensus labels for risk tolerance, risk capacity, liquidity need,
    suitability risk, recommended portfolio class and human escalation.
    No real client data.
"""

import csv
import json
import os
import sys
import urllib.request

DATASET_ID = "w48mh2dtg5"
API = "https://data.mendeley.com/public-api/datasets/%s/files?folder_id=root&version=1" % DATASET_ID
HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
XLSX = os.path.join(DATA_DIR, "ILS_Bench_Repository.xlsx")
CSV_OUT = os.path.join(DATA_DIR, "ils_bench_cases.csv")
JS_OUT = os.path.join(HERE, "..", "ils_bench_cases.js")

COLUMNS = [
    "Case_ID", "Investor_Narrative", "Evidence_Span", "Author_Portfolio", "Author_Escalation",
    "Consensus_Risk_Tolerance", "Consensus_Risk_Capacity", "Consensus_Liquidity_Need",
    "Consensus_Suitability_Risk", "Consensus_Portfolio", "Consensus_Escalation",
    "Agree_Count", "Disagree_Count", "Unsure_Count", "Review_Flag",
]


def download():
    os.makedirs(DATA_DIR, exist_ok=True)
    if os.path.exists(XLSX):
        print("using existing", XLSX)
        return
    print("querying Mendeley Data API")
    with urllib.request.urlopen(API) as r:
        files = json.load(r)
    url = None
    for f in files:
        if f.get("filename", "").endswith(".xlsx"):
            url = f["content_details"]["download_url"]
    if not url:
        sys.exit("could not find the xlsx file in the dataset listing")
    print("downloading", url)
    urllib.request.urlretrieve(url, XLSX)
    print("saved", XLSX)


def extract():
    try:
        import openpyxl
    except ImportError:
        sys.exit("please run: pip install openpyxl")
    wb = openpyxl.load_workbook(XLSX, read_only=True, data_only=True)
    ws = wb["Cases_Consensus"]
    rows = list(ws.iter_rows(values_only=True))
    header = list(rows[0])
    idx = {h: i for i, h in enumerate(header)}
    out = []
    for r in rows[1:]:
        if not r or r[idx["Case_ID"]] is None:
            continue
        out.append({c: ("" if r[idx[c]] is None else str(r[idx[c]])) for c in COLUMNS})
    with open(CSV_OUT, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        w.writeheader()
        w.writerows(out)
    print("wrote", CSV_OUT, len(out), "cases")

    compact = [
        {
            "id": o["Case_ID"],
            "narrative": o["Investor_Narrative"],
            "evidence": o["Evidence_Span"],
            "tolerance": o["Consensus_Risk_Tolerance"],
            "capacity": o["Consensus_Risk_Capacity"],
            "liquidity": o["Consensus_Liquidity_Need"],
            "suitabilityRisk": o["Consensus_Suitability_Risk"],
            "portfolio": o["Consensus_Portfolio"],
            "escalation": o["Consensus_Escalation"],
            "authorPortfolio": o["Author_Portfolio"],
            "reviewFlag": o["Review_Flag"],
        }
        for o in out
    ]
    with open(JS_OUT, "w", encoding="utf-8") as f:
        f.write("/* Generated by ml/fetch_ils_bench.py from ILS-Bench (Bonelli, 2026, Mendeley Data, doi:10.17632/w48mh2dtg5.1, CC BY 4.0). Do not edit by hand. */\n")
        f.write("window.AdviceIT = window.AdviceIT || {};\n")
        f.write("window.AdviceIT.ilsBench = ")
        f.write(json.dumps({"source": "ILS-Bench v1, Bonelli 2026, doi:10.17632/w48mh2dtg5.1, CC BY 4.0", "cases": compact}, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    print("wrote", os.path.normpath(JS_OUT))


if __name__ == "__main__":
    download()
    extract()
